// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: govalid.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Field-level validation options
type FieldValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []string               `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValidation) Reset() {
	*x = FieldValidation{}
	mi := &file_govalid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValidation) ProtoMessage() {}

func (x *FieldValidation) ProtoReflect() protoreflect.Message {
	mi := &file_govalid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValidation.ProtoReflect.Descriptor instead.
func (*FieldValidation) Descriptor() ([]byte, []int) {
	return file_govalid_proto_rawDescGZIP(), []int{0}
}

func (x *FieldValidation) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

var file_govalid_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldValidation)(nil),
		Field:         50001,
		Name:          "govalid.v1.govalid",
		Tag:           "bytes,50001,opt,name=govalid",
		Filename:      "govalid.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional govalid.v1.FieldValidation govalid = 50001;
	E_Govalid = &file_govalid_proto_extTypes[0]
)

var File_govalid_proto protoreflect.FileDescriptor

const file_govalid_proto_rawDesc = "" +
	"\n" +
	"\rgovalid.proto\x12\n" +
	"govalid.v1\x1a google/protobuf/descriptor.proto\"'\n" +
	"\x0fFieldValidation\x12\x14\n" +
	"\x05rules\x18\x01 \x03(\tR\x05rules:V\n" +
	"\agovalid\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x1b.govalid.v1.FieldValidationR\agovalidB6Z4github.com/khatibomar/protoc-gen-govalidwrapper;mainb\x06proto3"

var (
	file_govalid_proto_rawDescOnce sync.Once
	file_govalid_proto_rawDescData []byte
)

func file_govalid_proto_rawDescGZIP() []byte {
	file_govalid_proto_rawDescOnce.Do(func() {
		file_govalid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_govalid_proto_rawDesc), len(file_govalid_proto_rawDesc)))
	})
	return file_govalid_proto_rawDescData
}

var file_govalid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_govalid_proto_goTypes = []any{
	(*FieldValidation)(nil),           // 0: govalid.v1.FieldValidation
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_govalid_proto_depIdxs = []int32{
	1, // 0: govalid.v1.govalid:extendee -> google.protobuf.FieldOptions
	0, // 1: govalid.v1.govalid:type_name -> govalid.v1.FieldValidation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_govalid_proto_init() }
func file_govalid_proto_init() {
	if File_govalid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_govalid_proto_rawDesc), len(file_govalid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_govalid_proto_goTypes,
		DependencyIndexes: file_govalid_proto_depIdxs,
		MessageInfos:      file_govalid_proto_msgTypes,
		ExtensionInfos:    file_govalid_proto_extTypes,
	}.Build()
	File_govalid_proto = out.File
	file_govalid_proto_goTypes = nil
	file_govalid_proto_depIdxs = nil
}
